// <auto-generated>
//  This file is generated during version bump operations.
//  Do not edit manually; update via version management scripts.
// </auto-generated>

namespace NotebookAutomation.Cli;

internal static class VersionConstants
{
    /// <summary>
    /// The current plugin release (semantic) version synchronized with manifest.json.
    /// </summary>
    public const string PluginReleaseVersion = "0.1.0-beta.41";
}
