# .github/workflows/build-exe.yml

name: Build CLI EXEs

on:
  push:
    branches: [ main, master ]
    paths-ignore:
      - '.agentic-tools-mcp/**'
  pull_request:
    branches: [ main, master ]
    paths-ignore:
      - '.agentic-tools-mcp/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -e .
          pip install pyinstaller

      - name: Build all EXEs from .spec files
        run: |
          for spec in *.spec; do
            pyinstaller "$spec"
          done

      - name: Upload EXEs as workflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cli-executables
          path: dist/*
