name: Build and Package C# Version of the Notebook Automation Tool

on:
  push:
    branches:
      - master
    paths:
      - "src/c-sharp/**"
      - ".github/workflows/**"
      - "!.agentic-tools-mcp/**"
  pull_request:
    branches:
      - master
    paths:
      - "src/c-sharp/**"
      - ".github/workflows/**"
      - "!.agentic-tools-mcp/**"

# Control workflow execution retention - deletes workflow runs after 14 days
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Controls automatic cleanup of workflow runs
# Keeps only the 10 most recent workflow runs and deletes older runs
permissions:
  actions: write
  contents: read

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        dotnet-version: ["9.0.x"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Cache NuGet packages
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Restore dependencies
        run: dotnet restore src/c-sharp/NotebookAutomation.sln

      - name: Set build version
        id: version
        run: |
          $buildDate = Get-Date

          # Microsoft recommended format: major.minor.build.revision
          # where build is typically days since a base date and revision is seconds since midnight / 2

          # Calculate build number (days since Jan 1, 2024)
          $baseDate = Get-Date -Year 2024 -Month 1 -Day 1
          $daysSinceBase = [math]::Floor(($buildDate - $baseDate).TotalDays)

          # For CI builds, use GitHub run number as revision for traceability
          $revision = $env:GITHUB_RUN_NUMBER

          # Format version strings
          $major = 1
          $minor = 0

          # For NuGet package version (must be valid SemVer)
          $packageVersion = "$major.$minor.0"

          # For assembly version - must be a specific version for NuGet restore
          $assemblyVersion = "$major.$minor.0.0"

          # For file version - use MS recommended format
          $fileVersion = "$major.$minor.$daysSinceBase.$revision"

          echo "PACKAGE_VERSION=$packageVersion" >> $env:GITHUB_ENV
          echo "FILE_VERSION=$fileVersion" >> $env:GITHUB_ENV
          echo "ASSEMBLY_VERSION=$assemblyVersion" >> $env:GITHUB_ENV

          echo "Package Version: $packageVersion"
          echo "File Version: $fileVersion"
          echo "Assembly Version: $assemblyVersion"
        shell: pwsh

      - name: Build solution
        run: dotnet build src/c-sharp/NotebookAutomation.sln --configuration Release --no-restore /p:Version=${{ env.PACKAGE_VERSION }} /p:FileVersion=${{ env.FILE_VERSION }} /p:AssemblyVersion=${{ env.ASSEMBLY_VERSION }} /p:InformationalVersion=${{ env.FILE_VERSION }}

      - name: Run tests with coverage
        run: |
          # Run all tests in the solution with coverage collection using runsettings
          dotnet test src/c-sharp/NotebookAutomation.sln --configuration Release --no-build --logger "trx;LogFileName=test-results.trx" --collect:"XPlat Code Coverage" --settings coverlet.runsettings --results-directory TestResults/
        env:
          DOTNET_CLI_TELEMETRY_OPTOUT: 1

      - name: Generate coverage report
        uses: danielpalme/ReportGenerator-GitHub-Action@5.4.7
        with:
          reports: "TestResults/**/coverage.cobertura.xml"
          targetdir: "CoverageReport"
          reporttypes: "HtmlInline;Cobertura;MarkdownSummaryGithub;TextSummary"
          assemblyfilters: "+NotebookAutomation.*;-*.Tests"
          classfilters: "+*;-*Test*"
          filefilters: "+*"
          verbosity: "Info"
          title: "Notebook Automation Code Coverage Report"
          tag: "${{ github.run_number }}_${{ github.run_id }}"

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-windows
          path: TestResults/*.trx
          retention-days: 7 # Keep test results for 7 days

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report-windows
          path: CoverageReport/
          retention-days: 14 # Keep coverage reports for 14 days

      - name: Upload raw coverage results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-raw-windows
          path: TestResults/**/coverage.cobertura.xml
          retention-days: 7 # Keep raw coverage files for 7 days

      - name: Add coverage comment to PR
        if: github.event_name == 'pull_request'
        run: |
          if (Test-Path "CoverageReport/SummaryGithub.md") {
            gh pr comment $env:PR_NUMBER --body-file CoverageReport/SummaryGithub.md
          } else {
            echo "Coverage markdown summary not found, skipping PR comment"
          }
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
        shell: pwsh

      - name: Publish coverage in build summary
        if: always()
        run: |
          if (Test-Path "CoverageReport/SummaryGithub.md") {
            Get-Content "CoverageReport/SummaryGithub.md" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
          } else {
            echo "Coverage markdown summary not found, skipping build summary"
          }
        shell: pwsh

      - name: Publish single-file EXE (win-x64)
        if: always()
        run: |
          cd ${{ github.workspace }}
          dotnet publish src/c-sharp/NotebookAutomation.Cli/NotebookAutomation.Cli.csproj -c Release -r win-x64 /p:PublishSingleFile=true /p:SelfContained=true /p:Version=${{ env.PACKAGE_VERSION }} /p:FileVersion=${{ env.FILE_VERSION }} /p:AssemblyVersion=${{ env.ASSEMBLY_VERSION }} /p:InformationalVersion=${{ env.FILE_VERSION }} --output publish/win-x64

      - name: Publish single-file EXE (win-arm64)
        if: always()
        run: |
          cd ${{ github.workspace }}
          dotnet publish src/c-sharp/NotebookAutomation.Cli/NotebookAutomation.Cli.csproj -c Release -r win-arm64 /p:PublishSingleFile=true /p:SelfContained=true /p:Version=${{ env.PACKAGE_VERSION }} /p:FileVersion=${{ env.FILE_VERSION }} /p:AssemblyVersion=${{ env.ASSEMBLY_VERSION }} /p:InformationalVersion=${{ env.FILE_VERSION }} --output publish/win-arm64

      - name: Upload published single-file executables
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: published-executables
          path: |
            publish/win-x64/
            publish/win-arm64/
          retention-days: 14 # Keep executables for 14 days (longer than test artifacts)
