name: Cleanup Artifacts and Workflow Runs

on:
  # Run weekly on Sunday at midnight
  schedule:
    - cron: '0 0 * * 0'  
  # Allow manual triggering
  workflow_dispatch:

# Permissions needed for cleanup operations
permissions:
  actions: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 14
          keep_minimum_runs: 10
      
      - name: Delete old artifacts
        uses: c-hive/gha-remove-artifacts@v1
        with:
          age: '7 days'  # Remove artifacts older than 7 days
          skip-recent: 10  # Keep at least 10 recent artifacts
          skip-tags: true  # Don't remove artifacts from tagged releases
